services:
  db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: my_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0

volumes:
  db_data:
