services:
  db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: my_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: dockerfile.flask  # <== Убедись, что этот файл есть
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_APP: app.py

volumes:
  db_data:
